# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  workflow_dispatch:
  workflow_run:
      workflows: ["R-CMD-check"]
      types:
        - completed

name: Build Examples

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    name: 'ubuntu-latest (R release) [Pandoc 2.14.2]'

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 2.19.2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Build examples
        run: Rscript tools/website.R
        shell: bash

      - name: Clean source files for deployment
        run: |
          rm *.Rmd index.bib
        working-directory: inst/examples

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: inst/examples # The folder the action should deploy.
